---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/aplancar/aurora-michaela
name: aurora-michaela
description: My personal Aurora build with NordVPN and flatpaks
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest

modules:
  - from-file: common-modules.yml

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam

  - type: kargs
    kargs:
      - i915.enable_dpcd_backlight=3 # Fix for ROG laptop backlight not working on Linux

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
